version: "3"
services:
  app:
    container_name: go-awsclient
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 1323:1323
    volumes:
      - ./src:/go/app
    environment:
      - ENV=remote
      - LOCAL_UID=1000
      - LOCAL_GID=1000
